
services:
  backend:
    build: . 
    image: caueurbini/inclusive_city_hub_backend:latest
    container_name: inclusive_city_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin123456789}
      DB_NAME: ${DB_NAME:-inclusive_city_hub}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: inclusive_city_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123456789}
      POSTGRES_DB: ${DB_NAME:-inclusive_city_hub}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
